In [11]:
import numpy as np

In [12]:
X = np.array([[1,0,0],[5,1,0],[-2,3,1]])
Y = np.array([[4,-2,1],[0,3,7],[0,0,2]])
print(X)
print(Y)

[[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]
[[ 4 -2  1]
 [ 0  3  7]
 [ 0  0  2]]


In [13]:
def prod_matrnxn(X,Y,n):
    prod = np.zeros((n,n))
    for i in range(len(X)):
        for j in range(len(X)):
            sum_ = 0
            for k in range(len(X)):
                sum_ += X[i][k]*Y[k][j]
            prod[i][j] = sum_
    return prod

In [14]:
prod_matrnxn(X,Y,3)

array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 21.]])