In [9]:
import numpy as np

In [10]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [11]:
def GausSeidel(A,b,itmax=1000,error = 1e-10):
    M,N = A.shape
    x = np.zeros(N)
    it = 0
    r = np.linalg.norm(b - np.dot(A,x))
    while ( r > error and it < itmax ):
        it += 1
        x_ = (1 + x[1] + x[2])/3
        y = (3 + x_ - x[2])/3
        z = (7 - 2*x_ - y)/4
        x[0] = x_
        x[1] = y
        x[2] = z
        r = np.linalg.norm(b - np.dot(A,x))
    return x,r

In [12]:
x,r = GausSeidel(M,b)
x,r

(array([1., 1., 1.]), 5.8029729042420824e-11)